python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_138.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_138.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_143.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_143.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_144.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_144.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_145.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_145.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_146.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_146.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_147.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_147.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_148.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_148.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_150.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_150.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_151.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_151.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_152.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_152.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_169.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_169.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/LT_171.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_LT_171.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_138.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_138.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_142.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_142.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_143.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_143.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_144.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_144.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_146.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_146.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_147.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_147.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_150.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_150.nii.gz ../../registered_niftis
python register.py ../../nii_images/RT_153.nii.gz ../../nii_images/RT_152.nii.gz ../../nii_segmentations/20220316_updated_gt_segmentations/Segmentation_RT_152.nii.gz ../../registered_niftis
