python register.py ../nii_files/RT_153.nii.gz LT_169.nii.gz Segmentation_LT_169.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_138.nii.gz Segmentation_RT_138.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_138.nii.gz Segmentation_LT_138.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_142.nii.gz Segmentation_RT_142.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_151.nii.gz Segmentation_LT_151.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_143.nii.gz Segmentation_LT_143.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_152.nii.gz Segmentation_RT_152.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_146.nii.gz Segmentation_LT_146.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_148.nii.gz Segmentation_LT_148.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_147.nii.gz Segmentation_LT_147.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_144.nii.gz Segmentation_RT_144.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_147.nii.gz Segmentation_RT_147.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_143.nii.gz Segmentation_RT_143.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_146.nii.gz Segmentation_RT_146.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_145.nii.gz Segmentation_LT_145.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_144.nii.gz Segmentation_LT_144.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz RT_153.nii.gz Segmentation_RT_153.nii.gz ../test_imgs
python register.py ../nii_files/RT_153.nii.gz LT_171.nii.gz Segmentation_LT_171.nii.gz ../test_imgs
