python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_150.nii.gz ../NIFTI_Segmentations/Segmentation_RT_150.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_169.nii.gz ../NIFTI_Segmentations/Segmentation_LT_169.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_138.nii.gz ../NIFTI_Segmentations/Segmentation_RT_138.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_138.nii.gz ../NIFTI_Segmentations/Segmentation_LT_138.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_142.nii.gz ../NIFTI_Segmentations/Segmentation_RT_142.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_151.nii.gz ../NIFTI_Segmentations/Segmentation_LT_151.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_143.nii.gz ../NIFTI_Segmentations/Segmentation_LT_143.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_152.nii.gz ../NIFTI_Segmentations/Segmentation_RT_152.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_146.nii.gz ../NIFTI_Segmentations/Segmentation_LT_146.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_148.nii.gz ../NIFTI_Segmentations/Segmentation_LT_148.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_147.nii.gz ../NIFTI_Segmentations/Segmentation_LT_147.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_144.nii.gz ../NIFTI_Segmentations/Segmentation_RT_144.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_147.nii.gz ../NIFTI_Segmentations/Segmentation_RT_147.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_143.nii.gz ../NIFTI_Segmentations/Segmentation_RT_143.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_152.nii.gz ../NIFTI_Segmentations/Segmentation_LT_152.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_150.nii.gz ../NIFTI_Segmentations/Segmentation_LT_150.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_146.nii.gz ../NIFTI_Segmentations/Segmentation_RT_146.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_145.nii.gz ../NIFTI_Segmentations/Segmentation_LT_145.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_144.nii.gz ../NIFTI_Segmentations/Segmentation_LT_144.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/RT_153.nii.gz ../NIFTI_Segmentations/Segmentation_RT_153.nii.gz ../registered_niftis/
python register.py ../nii_files/RT_153.nii.gz ../nii_files/LT_171.nii.gz ../NIFTI_Segmentations/Segmentation_LT_171.nii.gz ../registered_niftis/
